---
- block:
    - name: Install GPG
      apt:
        name: gpg
        state: present
        update_cache: yes

    - name: Add PostgreSQL apt-key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL apt repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        state: present
        filename: postgres
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name: "postgresql-{{ postgresql_version }}"
        state: present
        update_cache: yes
  become: true
