---
- name: Include Debian-specific tasks
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include RedHat-specific tasks
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Display installation result
  debug:
    msg: "Installation on {{ inventory_hostname }} was successful"
